name: Create Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  
jobs:
  create-release:
    uses: liquibase/build-logic/.github/workflows/create-release.yml@DAT-18309
    secrets: inherit
