name: Release Extension to Sonatype

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write
  packages: write
  id-token: write

jobs:
  release:
    uses: liquibase/build-logic/.github/workflows/extension-release-published.yml@jandroav/dat-22608-release-fix
    secrets: inherit
    with:
      tag: "v5.0.2"
