name: "Test Automated Release (DAT-22608)"

on:
  workflow_dispatch:

permissions:
  contents: write
  security-events: read
  packages: write
  id-token: write

jobs:
  automated-release:
    uses: liquibase/build-logic/.github/workflows/extension-automated-release.yml@jandroav/dat-22608-release-fix
    secrets: inherit
    with:
      version: "5.0.2"
      repositories: '["liquibase-nochangeloglock"]'
